### ISSUE TITLE
Events.js error 

### ISSUE THREAD

**Issue by baddog2000** [aerohive/devices-details-to-csv#2]
events.js:174
      throw er; // Unhandled 'error' event
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Any idea how to resolve this issue

**Comment by baddog2000** [comment]
I am able to get a response from postman , it seems to be something with error handling.

**Comment by tmunzer** [comment]
Hi baddog2000,

Are you using a HM public cloud or HM local cloud?
From the logs it seems the certificate presented by the HM is a self-signed certificate, so I'm assuming it's a local cloud.
The script should automatically disable the certificate validation if the server is not on the Aerohive domain, but you can manually force this settings by adding the line below after your settings:
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

Regards,
Thomas
